### PR TITLE
Create pt.json

### PR DESCRIPTION
**Pull request by ViPeR5000**

### CODE REVIEW

**Comment by MTrab** [comment]
I'll keep this on hold, as all translations will be done from Lokalise, when I get around to setup the project.

**Comment by ViPeR5000** [comment]
> I'll keep this on hold, as all translations will be done from Lokalise, when I get around to setup the project.

if u want share the link of the project @ Lokalise

**Comment by MTrab** [comment]
It will be linked from the README (frontpage of this repo) as soon as I have created the project

**Comment by ViPeR5000** [comment]
> It will be linked from the README (frontpage of this repo) as soon as I have created the project

Sorry :(

**Comment by MTrab** [comment]
Lokalise project online on this link: https://app.lokalise.com/public/25546617659fd91f4f8358.30009801/

**Pull request closed without merging**
